- name: Getting the server up to date
  hosts: myhosts
  remote_user: jirka_srv
  become_method: sudo
  become_user: root

  vars:
    project_dir: "/home/jirka_srv/Docker_stuff/Jellyfin"
    domain_name: "sky-viewer.app"
    email_address: "jiri.kolenaty@datamole.cz"
    users:
      - github_user: kfiala-dtml
        system_user: root
      - github_user: tklas-dtml
        system_user: root
    project_paths:
      - "/home/{{ansible_user}}/Docker_stuff/Jellyfin"
      - "/home/{{ansible_user}}/Docker_stuff/Jellyfin/cache"
      - "/home/{{ansible_user}}/Docker_stuff/Jellyfin/config"
      - "/home/{{ansible_user}}/Docker_stuff/Jellyfin/media"
      - "/home/{{ansible_user}}/Docker_stuff/Jellyfin/media/movies"
      - "/home/{{ansible_user}}/Docker_stuff/Jellyfin/media/tvshows"
    nginx_paths:
      - src: "{{playbook_dir}}/server-files/Jellyfin/jellyfin.conf"
        dest: "/etc/nginx/conf.d/jellyfin.conf"
      - src: "{{playbook_dir}}/server-files/Jellyfin/sky-viewer.app"
        dest: "/etc/nginx/sites-available/sky-viewer.app"


  tasks:

    - name: Fetch SSH keys and add them to root's authorized_keys
      ansible.posix.authorized_key:
        user: "{{ item.system_user }}"
        key: "https://github.com/{{ item.github_user }}.keys"
        state: present
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.system_user }}"
      become: true

    - name: Set Timezone and time to Prague
      community.general.timezone:
        name: Europe/Prague
        hwclock: UTC
      become: true

    - name: pkg update && upgrade
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        cache_valid_time: 3600
        upgrade: safe
      become: true

    - name: Sync needed system packages
      ansible.builtin.apt:
        force_apt_get: true
        name:          
          - docker.io
          - htop
          - vim
          - curl
          - btop
          - nginx
          - certbot
      become: true

    - name: make project directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop: "{{ project_paths }}"


    - name: Copy the Nginx config file for Jellyfin
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ nginx_paths }}"
      become: true

    - name: copy docker-compose.yml file to the server
      ansible.builtin.copy:
        src: "{{playbook_dir}}/server-files/Jellyfin/docker-compose.yml"
        dest: "/home/{{ansible_user}}/Docker_stuff/docker-compose.yml"

    - name: Start the whole docker-compose.yml file
      community.docker.docker_compose_v2:
        project_src: /home/jirka_srv/Docker_stuff
        # in-case of wanting to start a single service, you can use the services: parameter like shown below
        # services:
        #   - [service_name]
        state: present