- name: Getting the server up to date
  hosts: myhosts
  remote_user: jirka_srv
  become_method: sudo
  become_user: root

  vars:
    users:
      - github_user: kfiala-dtml
        system_user: root
      - github_user: tklas-dtml
        system_user: root

  tasks:

    - name: Fetch SSH keys and add them to root's authorized_keys
      ansible.posix.authorized_key:
        user: "{{ item.system_user }}"
        key: "https://github.com/{{ item.github_user }}.keys"
        state: present
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.system_user }}"
      become: true

    - name: Set Timezone and time to Prague
      community.general.timezone:
        name: Europe/Prague
        hwclock: UTC
      become: true

    - name: pkg update && upgrade
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        cache_valid_time: 3600
        upgrade: safe
      become: true

    - name: Sync needed packages
      ansible.builtin.apt:
        force_apt_get: true
        name:          
          - docker.io
          - htop
          - vim
          - curl
          - btop
          - nginx
          - certbot
      become: true

    - name: Start a whole docker-compose.yml file
      community.docker.docker_compose_v2:
        project_src: /home/jirka_srv/Jellyfin_[docker]
        # in-case of wanting to start a single service, you can use the services: parameter like shown below
        # services:
        #   - [service_name]
        state: present