services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.8
    container_name: Jellyfin
    user: 1000:1000
    volumes:
      - ./Jellyfin/config:/config
      - ./Jellyfin/cache:/cache
      - ./Jellyfin/media/movies:/media/movies
      - ./Jellyfin/media/tvshows:/media/tvshows
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    # TODO: 1.31.0 is a mainline (development) release of nginx. For production
    # prefer a stable branch release, can be left here. ;)
    image: nginx:1.30.1
    container_name: reverse-proxy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Healthcheck added :D
    depends_on:
       jellyfin:
          condition: service_healthy
    # The 1st SSL certificate will be generated manually, that's why certbot will automatically download. :3

  certbot:
    image: certbot/certbot:v5.6.0
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
