services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.8
    container_name: Jellyfin
    user: 1000:1000
    volumes:
      - ./Jellyfin/config:/config
      - ./Jellyfin/cache:/cache
      - ./Jellyfin/media/movies:/media/movies
      - ./Jellyfin/media/tvshows:/media/tvshows
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.31.0
    container_name: reverse-proxy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    depends_on:
       jellyfin:
          condition: service_healthy