server {
    listen 80;
    listen [::]:80;
    server_name sky-viewer.app;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        # Fixed the mounting. :>
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

# Hope  i applied most of the flags correctly
# https://github.com/fialakarel/docker-nginx/blob/master/example.com.conf-sample

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;  # good — HTTP/2 enabled

    server_name sky-viewer.app; 

    ssl_certificate /etc/letsencrypt/live/sky-viewer.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sky-viewer.app/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_stapling on;                    #Added this          
    ssl_stapling_verify on;             #Added this
    ssl_session_timeout 5m;             #Added this
    ssl_session_cache shared:SSL:10m;   #Added this
    client_max_body_size 20m;           #Added this
    client_body_buffer_size 128k;       #Added this

    location / {
        proxy_pass http://jellyfin:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    }
}
