services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: Jellyfin
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media/movies:/media/movies
      - ./media/tvshows:/media/tvshows
    restart: unless-stopped